name: Build and Upload Adblock Buffer

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Чеккаут кода
        uses: actions/checkout@v4

      - name: Установка Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Установка зависимостей
        run: npm ci

      - name: Сборка файлов блокировки
        run: node build-blocker.js

      - name: Отправка файлов на сервер по SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "adblocker.bin,android-filters.txt"
          target: "/var/www/html/updates/"
